
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		cover_
	 *	@date 		Monday 10th of October 2022 02:35:30 PM
	 *	@title 		Wireframe
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.figma
	 *
	 */
	

package exportkit.figma;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

public class home_activity extends Activity {

	
	private View _bg__home_ek2;
	private TextView title;
	private ImageView blob;
	private ImageView whites;
	private View highlights;
	private View highlights_ek1;
	private ImageView stroke;
	private ImageView stroke_ek1;
	private ImageView highlights_ek2;
	private ImageView stroke_ek2;
	private View ellipse_2;
	private TextView play;
	private View ellipse_3;
	private TextView title_ek1;
	private ImageView blob_ek1;
	private ImageView whites_ek1;
	private ImageView highlights_ek3;
	private ImageView highlights_ek4;
	private ImageView stroke_ek3;
	private ImageView stroke_ek4;
	private ImageView stroke_ek5;
	private ImageView stroke_ek6;
	private ImageView stroke_ek7;
	private ImageView stroke_ek8;
	private ImageView highlights_ek5;
	private ImageView highlights_ek6;
	private ImageView stroke_ek9;
	private ImageView stroke_ek10;
	private ImageView stroke_ek11;
	private ImageView stroke_ek12;
	private ImageView stroke_ek13;
	private ImageView stroke_ek14;
	private ImageView stroke_ek15;
	private ImageView stroke_ek16;
	private ImageView stroke_ek17;
	private ImageView stroke_ek18;
	private ImageView stroke_ek19;
	private ImageView stroke_ek20;
	private ImageView stroke_ek21;
	private ImageView stroke_ek22;
	private ImageView stroke_ek23;
	private ImageView stroke_ek24;
	private ImageView highlights_ek7;
	private ImageView highlights_ek8;
	private ImageView highlights_ek9;
	private View ellipse_2_ek1;
	private TextView play_ek1;
	private View ellipse_3_ek1;
	private TextView recent_ek1;
	private TextView categories;
	private TextView see_all__;
	private TextView text;
	private ImageView vector_ek5;
	private ImageView vector_ek6;
	private ImageView vector_ek7;
	private ImageView vector_ek8;
	private ImageView vector_ek9;
	private ImageView vector_ek10;
	private ImageView vector_ek11;
	private ImageView vector_ek12;
	private ImageView vector_ek13;
	private ImageView vector_ek14;
	private ImageView vector_ek15;
	private ImageView vector_ek16;
	private ImageView vector_ek17;
	private ImageView vector_ek18;
	private ImageView vector_ek19;
	private ImageView vector_ek20;
	private ImageView vector_ek21;
	private ImageView vector_ek22;
	private ImageView vector_ek23;
	private ImageView vector_ek24;
	private ImageView vector_ek25;
	private ImageView vector_ek26;
	private ImageView vector_ek27;
	private ImageView vector_ek28;
	private ImageView vector_ek29;
	private ImageView vector_ek30;
	private ImageView vector_ek31;
	private ImageView vector_ek32;
	private ImageView vector_ek33;
	private ImageView vector_ek34;
	private ImageView vector_ek35;
	private ImageView vector_ek36;
	private ImageView vector_ek37;
	private ImageView vector_ek38;
	private ImageView vector_ek39;
	private ImageView vector_ek40;
	private ImageView vector_ek41;
	private ImageView vector_ek42;
	private ImageView vector_ek43;
	private ImageView vector_ek44;
	private ImageView vector_ek45;
	private ImageView vector_ek46;
	private ImageView vector_ek47;
	private ImageView vector_ek48;
	private ImageView vector_ek49;
	private ImageView vector_ek50;
	private ImageView vector_ek51;
	private ImageView vector_ek52;
	private ImageView vector_ek53;
	private ImageView vector_ek54;
	private ImageView vector_ek55;
	private ImageView vector_ek56;
	private ImageView vector_ek57;
	private ImageView vector_ek58;
	private ImageView vector_ek59;
	private ImageView vector_ek60;
	private ImageView vector_ek61;
	private ImageView vector_ek62;
	private ImageView vector_ek63;
	private ImageView vector_ek64;
	private ImageView vector_ek65;
	private ImageView vector_ek66;
	private ImageView vector_ek67;
	private ImageView vector_ek68;
	private ImageView vector_ek69;
	private ImageView vector_ek70;
	private ImageView vector_ek71;
	private ImageView vector_ek72;
	private ImageView vector_ek73;
	private ImageView vector_ek74;
	private ImageView vector_ek75;
	private ImageView vector_ek76;
	private ImageView vector_ek77;
	private TextView text_ek1;
	private ImageView vector_ek78;
	private ImageView vector_ek79;
	private ImageView vector_ek80;
	private ImageView vector_ek81;
	private ImageView vector_ek82;
	private ImageView vector_ek83;
	private ImageView vector_ek84;
	private ImageView vector_ek85;
	private ImageView vector_ek86;
	private ImageView vector_ek87;
	private ImageView vector_ek88;
	private ImageView vector_ek89;
	private ImageView vector_ek90;
	private ImageView vector_ek91;
	private ImageView vector_ek92;
	private ImageView vector_ek93;
	private ImageView vector_ek94;
	private ImageView vector_ek95;
	private ImageView vector_ek96;
	private ImageView vector_ek97;
	private ImageView vector_ek98;
	private ImageView vector_ek99;
	private ImageView vector_ek100;
	private ImageView vector_ek101;
	private ImageView vector_ek102;
	private ImageView vector_ek103;
	private ImageView vector_ek104;
	private ImageView vector_ek105;
	private ImageView vector_ek106;
	private ImageView vector_ek107;
	private ImageView vector_ek108;
	private ImageView vector_ek109;
	private ImageView vector_ek110;
	private ImageView vector_ek111;
	private ImageView vector_ek112;
	private ImageView vector_ek113;
	private ImageView vector_ek114;
	private ImageView vector_ek115;
	private ImageView vector_ek116;
	private ImageView vector_ek117;
	private ImageView vector_ek118;
	private ImageView vector_ek119;
	private ImageView vector_ek120;
	private ImageView vector_ek121;
	private ImageView vector_ek122;
	private ImageView vector_ek123;
	private ImageView vector_ek124;
	private ImageView vector_ek125;
	private ImageView vector_ek126;
	private ImageView vector_ek127;
	private ImageView vector_ek128;
	private ImageView hand;
	private TextView text_ek2;
	private ImageView vector_ek129;
	private ImageView vector_ek130;
	private ImageView vector_ek131;
	private ImageView vector_ek132;
	private ImageView vector_ek133;
	private ImageView vector_ek134;
	private ImageView vector_ek135;
	private ImageView vector_ek136;
	private ImageView vector_ek137;
	private ImageView vector_ek138;
	private ImageView vector_ek139;
	private ImageView vector_ek140;
	private ImageView vector_ek141;
	private ImageView vector_ek142;
	private ImageView vector_ek143;
	private ImageView vector_ek144;
	private TextView text_ek3;
	private ImageView vector_ek145;
	private ImageView vector_ek146;
	private ImageView vector_ek147;
	private ImageView vector_ek148;
	private ImageView vector_ek149;
	private ImageView vector_ek150;
	private ImageView vector_ek151;
	private ImageView vector_ek152;
	private ImageView vector_ek153;
	private ImageView vector_ek154;
	private ImageView vector_ek155;
	private ImageView vector_ek156;
	private ImageView vector_ek157;
	private ImageView vector_ek158;
	private ImageView vector_ek159;
	private ImageView vector_ek160;
	private ImageView vector_ek161;
	private ImageView vector_ek162;
	private ImageView vector_ek163;
	private ImageView vector_ek164;
	private ImageView vector_ek165;
	private ImageView vector_ek166;
	private ImageView vector_ek167;
	private ImageView vector_ek168;
	private ImageView vector_ek169;
	private ImageView vector_ek170;
	private ImageView vector_ek171;
	private ImageView vector_ek172;
	private ImageView vector_ek173;
	private ImageView vector_ek174;
	private ImageView vector_ek175;
	private TextView listen_and_learn;
	private ImageView vector_ek189;
	private ImageView vector_ek190;
	private ImageView vector_ek191;
	private ImageView vector_ek192;
	private ImageView vector_ek193;
	private ImageView vector_ek194;
	private ImageView vector_ek195;
	private ImageView vector_ek196;
	private ImageView vector_ek197;
	private ImageView vector_ek198;
	private ImageView vector_ek199;
	private ImageView vector_ek200;
	private ImageView vector_ek201;
	private ImageView vector_ek202;
	private ImageView vector_ek203;
	private ImageView vector_ek204;
	private ImageView vector_ek205;
	private ImageView vector_ek206;
	private ImageView vector_ek207;
	private ImageView vector_ek208;
	private ImageView vector_ek209;
	private ImageView vector_ek210;
	private ImageView vector_ek211;
	private ImageView vector_ek212;
	private ImageView vector_ek213;
	private ImageView vector_ek214;
	private ImageView vector_ek215;
	private TextView _100;
	private ImageView blob_ek6;
	private ImageView path;
	private ImageView path_ek1;
	private ImageView shape;
	private ImageView oval;
	private ImageView oval_copy;
	private ImageView shape_ek1;
	private ImageView path_30;
	private ImageView shape_ek2;
	private ImageView path_ek2;
	private ImageView path_ek3;
	private TextView listen_and_learn_ek1;
	private ImageView vector_ek216;
	private ImageView vector_ek217;
	private ImageView vector_ek218;
	private ImageView vector_ek219;
	private ImageView vector_ek220;
	private ImageView vector_ek221;
	private ImageView vector_ek222;
	private ImageView vector_ek223;
	private ImageView vector_ek224;
	private ImageView vector_ek225;
	private ImageView vector_ek226;
	private ImageView vector_ek227;
	private ImageView vector_ek228;
	private ImageView vector_ek229;
	private ImageView vector_ek230;
	private ImageView vector_ek231;
	private ImageView vector_ek232;
	private ImageView vector_ek233;
	private ImageView vector_ek234;
	private ImageView vector_ek235;
	private ImageView vector_ek236;
	private ImageView vector_ek237;
	private ImageView vector_ek238;
	private ImageView vector_ek239;
	private ImageView vector_ek240;
	private ImageView vector_ek241;
	private ImageView vector_ek242;
	private TextView _100_ek1;
	private TextView new_games_ek1;
	private ImageView vector_ek243;
	private TextView subitle;
	private ImageView vector_ek244;
	private ImageView vector_ek245;
	private ImageView vector_ek246;
	private ImageView vector_ek247;
	private ImageView vector_ek248;
	private ImageView vector_ek249;
	private ImageView vector_ek250;
	private ImageView vector_ek251;
	private ImageView vector_ek252;
	private ImageView vector_ek253;
	private ImageView vector_ek254;
	private ImageView vector_ek255;
	private ImageView vector_ek256;
	private ImageView vector_ek257;
	private ImageView vector_ek258;
	private ImageView vector_ek259;
	private ImageView vector_ek260;
	private ImageView vector_ek261;
	private ImageView vector_ek262;
	private ImageView vector_ek263;
	private ImageView vector_ek264;
	private ImageView vector_ek265;
	private ImageView vector_ek266;
	private ImageView vector_ek267;
	private ImageView vector_ek268;
	private ImageView vector_ek269;
	private ImageView vector_ek270;
	private ImageView vector_ek271;
	private ImageView vector_ek272;
	private TextView listen_and_learn_ek2;
	private ImageView vector_ek273;
	private ImageView vector_ek274;
	private ImageView vector_ek275;
	private ImageView vector_ek276;
	private ImageView vector_ek277;
	private ImageView vector_ek278;
	private ImageView vector_ek279;
	private ImageView vector_ek280;
	private ImageView vector_ek281;
	private ImageView vector_ek282;
	private ImageView vector_ek283;
	private ImageView vector_ek284;
	private ImageView vector_ek285;
	private ImageView vector_ek286;
	private ImageView vector_ek287;
	private ImageView vector_ek288;
	private ImageView vector_ek289;
	private ImageView vector_ek290;
	private ImageView vector_ek291;
	private ImageView vector_ek292;
	private ImageView vector_ek293;
	private ImageView vector_ek294;
	private ImageView vector_ek295;
	private ImageView vector_ek296;
	private ImageView vector_ek297;
	private ImageView vector_ek298;
	private ImageView vector_ek299;
	private TextView _100_ek2;
	private ImageView blob_ek7;
	private ImageView whites_ek2;
	private ImageView whites_ek3;
	private ImageView shadow;
	private ImageView whites_ek4;
	private ImageView shadow_ek1;
	private ImageView stroke_ek25;
	private ImageView whites_ek5;
	private ImageView shape_ek3;
	private ImageView shadow_ek2;
	private ImageView shape_ek4;
	private ImageView whites_ek6;
	private ImageView whites_ek7;
	private ImageView whites_ek8;
	private ImageView whites_ek9;
	private ImageView whites_ek10;
	private ImageView whites_ek11;
	private ImageView whites_ek12;
	private ImageView whites_ek13;
	private ImageView whites_ek14;
	private ImageView whites_ek15;
	private ImageView whites_ek16;
	private ImageView whites_ek17;
	private ImageView whites_ek18;
	private ImageView whites_ek19;
	private ImageView whites_ek20;
	private ImageView whites_ek21;
	private ImageView whites_ek22;
	private ImageView whites_ek23;
	private ImageView whites_ek24;
	private ImageView whites_ek25;
	private ImageView whites_ek26;
	private ImageView whites_ek27;
	private ImageView whites_ek28;
	private ImageView whites_ek29;
	private ImageView whites_ek30;
	private ImageView whites_ek31;
	private ImageView whites_ek32;
	private ImageView whites_ek33;
	private ImageView whites_ek34;
	private ImageView whites_ek35;
	private ImageView whites_ek36;
	private ImageView whites_ek37;
	private ImageView whites_ek38;
	private ImageView whites_ek39;
	private ImageView whites_ek40;
	private ImageView whites_ek41;
	private ImageView whites_ek42;
	private ImageView whites_ek43;
	private ImageView whites_ek44;
	private ImageView whites_ek45;
	private ImageView whites_ek46;
	private ImageView whites_ek47;
	private ImageView whites_ek48;
	private ImageView whites_ek49;
	private ImageView whites_ek50;
	private ImageView whites_ek51;
	private ImageView whites_ek52;
	private ImageView whites_ek53;
	private ImageView whites_ek54;
	private ImageView whites_ek55;
	private ImageView whites_ek56;
	private ImageView whites_ek57;
	private ImageView whites_ek58;
	private ImageView whites_ek59;
	private ImageView whites_ek60;
	private ImageView whites_ek61;
	private ImageView whites_ek62;
	private ImageView whites_ek63;
	private ImageView whites_ek64;
	private ImageView whites_ek65;
	private ImageView whites_ek66;
	private ImageView whites_ek67;
	private ImageView whites_ek68;
	private ImageView whites_ek69;
	private ImageView whites_ek70;
	private ImageView whites_ek71;
	private ImageView whites_ek72;
	private ImageView whites_ek73;
	private ImageView whites_ek74;
	private ImageView whites_ek75;
	private ImageView whites_ek76;
	private ImageView whites_ek77;
	private ImageView whites_ek78;
	private ImageView whites_ek79;
	private ImageView stroke_ek26;
	private ImageView stroke_ek27;
	private ImageView stroke_ek28;
	private ImageView whites_ek80;
	private ImageView shape_ek5;
	private ImageView whites_ek81;
	private ImageView whites_ek82;
	private ImageView shadow_ek3;
	private ImageView shadow_ek4;
	private TextView listen_and_learn_ek3;
	private ImageView vector_ek300;
	private ImageView vector_ek301;
	private ImageView vector_ek302;
	private ImageView vector_ek303;
	private ImageView vector_ek304;
	private ImageView vector_ek305;
	private ImageView vector_ek306;
	private ImageView vector_ek307;
	private ImageView vector_ek308;
	private ImageView vector_ek309;
	private ImageView vector_ek310;
	private ImageView vector_ek311;
	private ImageView vector_ek312;
	private ImageView vector_ek313;
	private ImageView vector_ek314;
	private ImageView vector_ek315;
	private ImageView vector_ek316;
	private ImageView vector_ek317;
	private ImageView vector_ek318;
	private ImageView vector_ek319;
	private ImageView vector_ek320;
	private ImageView vector_ek321;
	private ImageView vector_ek322;
	private ImageView vector_ek323;
	private ImageView vector_ek324;
	private ImageView vector_ek325;
	private ImageView vector_ek326;
	private TextView _100_ek3;
	private ImageView blob_ek8;
	private ImageView vector_ek327;
	private ImageView vector_ek328;
	private ImageView vector_ek329;
	private ImageView vector_ek330;
	private ImageView vector_ek331;
	private ImageView vector_ek332;
	private ImageView vector_ek333;
	private ImageView vector_ek334;
	private ImageView vector_ek335;
	private ImageView vector_ek336;
	private ImageView vector_ek337;
	private ImageView vector_ek338;
	private ImageView vector_ek339;
	private ImageView vector_ek340;
	private ImageView vector_ek341;
	private ImageView vector_ek342;
	private ImageView vector_ek343;
	private ImageView vector_ek344;
	private ImageView vector_ek345;
	private ImageView vector_ek346;
	private ImageView vector_ek347;
	private ImageView vector_ek348;
	private ImageView vector_ek349;
	private ImageView vector_ek350;
	private ImageView vector_ek351;
	private TextView listen_and_learn_ek4;
	private ImageView vector_ek352;
	private ImageView vector_ek353;
	private ImageView vector_ek354;
	private ImageView vector_ek355;
	private ImageView vector_ek356;
	private ImageView vector_ek357;
	private ImageView vector_ek358;
	private ImageView vector_ek359;
	private ImageView vector_ek360;
	private ImageView vector_ek361;
	private ImageView vector_ek362;
	private ImageView vector_ek363;
	private ImageView vector_ek364;
	private ImageView vector_ek365;
	private ImageView vector_ek366;
	private ImageView vector_ek367;
	private ImageView vector_ek368;
	private ImageView vector_ek369;
	private ImageView vector_ek370;
	private ImageView vector_ek371;
	private ImageView vector_ek372;
	private ImageView vector_ek373;
	private ImageView vector_ek374;
	private ImageView vector_ek375;
	private ImageView vector_ek376;
	private ImageView vector_ek377;
	private ImageView vector_ek378;
	private TextView _100_ek4;
	private View rectangle_6;
	private ImageView vector_ek379;
	private TextView complete_other_games_to_unlock;
	private ImageView vector_ek380;
	private ImageView vector_ek381;
	private ImageView vector_ek382;
	private ImageView vector_ek383;
	private ImageView vector_ek384;
	private ImageView vector_ek385;
	private ImageView vector_ek386;
	private ImageView vector_ek387;
	private ImageView vector_ek388;
	private TextView discover_ek1;
	private ImageView vector_ek389;
	private ImageView vector_ek390;
	private ImageView vector_ek391;
	private ImageView vector_ek392;
	private ImageView vector_ek393;
	private ImageView vector_ek394;
	private ImageView vector_ek395;
	private ImageView vector_ek396;
	private TextView search_ek1;
	private ImageView vector_ek397;
	private ImageView vector_ek398;
	private ImageView vector_ek399;
	private ImageView vector_ek400;
	private TextView favorites;
	private ImageView vector_ek401;
	private ImageView vector_ek402;
	private ImageView vector_ek403;
	private ImageView vector_ek404;
	private ImageView vector_ek405;
	private ImageView vector_ek406;
	private ImageView vector_ek407;
	private ImageView vector_ek408;
	private ImageView vector_ek409;
	private ImageView vector_ek410;
	private ImageView vector_ek411;
	private ImageView vector_ek412;
	private ImageView vector_ek413;
	private ImageView vector_ek414;
	private ImageView vector_ek415;
	private ImageView vector_ek416;
	private TextView profile_ek1;
	private View home_indicator_ek1;
	private ImageView rectangle_69;
	private ImageView treasure_chest;
	private TextView _1432_xp;
	private ImageView fire;
	private TextView _3;
	private ImageView stitched_heart;
	private TextView _7;
	private ImageView diamond;
	private TextView _22;
	private ImageView woman_chilling_on_vacation_in_a_pool_ring_with_cocktail;
	private ImageView _9_41_ek1;
	private ImageView rectangle_ek2;
	private ImageView combined_shape_ek1;
	private ImageView rectangle_ek3;
	private ImageView wifi_ek1;
	private ImageView mobile_signal_ek1;
	private View indicator_ek1;
	private TextView welcome_back_;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.home);

		
		_bg__home_ek2 = (View) findViewById(R.id._bg__home_ek2);
		title = (TextView) findViewById(R.id.title);
		blob = (ImageView) findViewById(R.id.blob);
		whites = (ImageView) findViewById(R.id.whites);
		highlights = (View) findViewById(R.id.highlights);
		highlights_ek1 = (View) findViewById(R.id.highlights_ek1);
		stroke = (ImageView) findViewById(R.id.stroke);
		stroke_ek1 = (ImageView) findViewById(R.id.stroke_ek1);
		highlights_ek2 = (ImageView) findViewById(R.id.highlights_ek2);
		stroke_ek2 = (ImageView) findViewById(R.id.stroke_ek2);
		ellipse_2 = (View) findViewById(R.id.ellipse_2);
		play = (TextView) findViewById(R.id.play);
		ellipse_3 = (View) findViewById(R.id.ellipse_3);
		title_ek1 = (TextView) findViewById(R.id.title_ek1);
		blob_ek1 = (ImageView) findViewById(R.id.blob_ek1);
		whites_ek1 = (ImageView) findViewById(R.id.whites_ek1);
		highlights_ek3 = (ImageView) findViewById(R.id.highlights_ek3);
		highlights_ek4 = (ImageView) findViewById(R.id.highlights_ek4);
		stroke_ek3 = (ImageView) findViewById(R.id.stroke_ek3);
		stroke_ek4 = (ImageView) findViewById(R.id.stroke_ek4);
		stroke_ek5 = (ImageView) findViewById(R.id.stroke_ek5);
		stroke_ek6 = (ImageView) findViewById(R.id.stroke_ek6);
		stroke_ek7 = (ImageView) findViewById(R.id.stroke_ek7);
		stroke_ek8 = (ImageView) findViewById(R.id.stroke_ek8);
		highlights_ek5 = (ImageView) findViewById(R.id.highlights_ek5);
		highlights_ek6 = (ImageView) findViewById(R.id.highlights_ek6);
		stroke_ek9 = (ImageView) findViewById(R.id.stroke_ek9);
		stroke_ek10 = (ImageView) findViewById(R.id.stroke_ek10);
		stroke_ek11 = (ImageView) findViewById(R.id.stroke_ek11);
		stroke_ek12 = (ImageView) findViewById(R.id.stroke_ek12);
		stroke_ek13 = (ImageView) findViewById(R.id.stroke_ek13);
		stroke_ek14 = (ImageView) findViewById(R.id.stroke_ek14);
		stroke_ek15 = (ImageView) findViewById(R.id.stroke_ek15);
		stroke_ek16 = (ImageView) findViewById(R.id.stroke_ek16);
		stroke_ek17 = (ImageView) findViewById(R.id.stroke_ek17);
		stroke_ek18 = (ImageView) findViewById(R.id.stroke_ek18);
		stroke_ek19 = (ImageView) findViewById(R.id.stroke_ek19);
		stroke_ek20 = (ImageView) findViewById(R.id.stroke_ek20);
		stroke_ek21 = (ImageView) findViewById(R.id.stroke_ek21);
		stroke_ek22 = (ImageView) findViewById(R.id.stroke_ek22);
		stroke_ek23 = (ImageView) findViewById(R.id.stroke_ek23);
		stroke_ek24 = (ImageView) findViewById(R.id.stroke_ek24);
		highlights_ek7 = (ImageView) findViewById(R.id.highlights_ek7);
		highlights_ek8 = (ImageView) findViewById(R.id.highlights_ek8);
		highlights_ek9 = (ImageView) findViewById(R.id.highlights_ek9);
		ellipse_2_ek1 = (View) findViewById(R.id.ellipse_2_ek1);
		play_ek1 = (TextView) findViewById(R.id.play_ek1);
		ellipse_3_ek1 = (View) findViewById(R.id.ellipse_3_ek1);
		recent_ek1 = (TextView) findViewById(R.id.recent_ek1);
		categories = (TextView) findViewById(R.id.categories);
		see_all__ = (TextView) findViewById(R.id.see_all__);
		text = (TextView) findViewById(R.id.text);
		vector_ek5 = (ImageView) findViewById(R.id.vector_ek5);
		vector_ek6 = (ImageView) findViewById(R.id.vector_ek6);
		vector_ek7 = (ImageView) findViewById(R.id.vector_ek7);
		vector_ek8 = (ImageView) findViewById(R.id.vector_ek8);
		vector_ek9 = (ImageView) findViewById(R.id.vector_ek9);
		vector_ek10 = (ImageView) findViewById(R.id.vector_ek10);
		vector_ek11 = (ImageView) findViewById(R.id.vector_ek11);
		vector_ek12 = (ImageView) findViewById(R.id.vector_ek12);
		vector_ek13 = (ImageView) findViewById(R.id.vector_ek13);
		vector_ek14 = (ImageView) findViewById(R.id.vector_ek14);
		vector_ek15 = (ImageView) findViewById(R.id.vector_ek15);
		vector_ek16 = (ImageView) findViewById(R.id.vector_ek16);
		vector_ek17 = (ImageView) findViewById(R.id.vector_ek17);
		vector_ek18 = (ImageView) findViewById(R.id.vector_ek18);
		vector_ek19 = (ImageView) findViewById(R.id.vector_ek19);
		vector_ek20 = (ImageView) findViewById(R.id.vector_ek20);
		vector_ek21 = (ImageView) findViewById(R.id.vector_ek21);
		vector_ek22 = (ImageView) findViewById(R.id.vector_ek22);
		vector_ek23 = (ImageView) findViewById(R.id.vector_ek23);
		vector_ek24 = (ImageView) findViewById(R.id.vector_ek24);
		vector_ek25 = (ImageView) findViewById(R.id.vector_ek25);
		vector_ek26 = (ImageView) findViewById(R.id.vector_ek26);
		vector_ek27 = (ImageView) findViewById(R.id.vector_ek27);
		vector_ek28 = (ImageView) findViewById(R.id.vector_ek28);
		vector_ek29 = (ImageView) findViewById(R.id.vector_ek29);
		vector_ek30 = (ImageView) findViewById(R.id.vector_ek30);
		vector_ek31 = (ImageView) findViewById(R.id.vector_ek31);
		vector_ek32 = (ImageView) findViewById(R.id.vector_ek32);
		vector_ek33 = (ImageView) findViewById(R.id.vector_ek33);
		vector_ek34 = (ImageView) findViewById(R.id.vector_ek34);
		vector_ek35 = (ImageView) findViewById(R.id.vector_ek35);
		vector_ek36 = (ImageView) findViewById(R.id.vector_ek36);
		vector_ek37 = (ImageView) findViewById(R.id.vector_ek37);
		vector_ek38 = (ImageView) findViewById(R.id.vector_ek38);
		vector_ek39 = (ImageView) findViewById(R.id.vector_ek39);
		vector_ek40 = (ImageView) findViewById(R.id.vector_ek40);
		vector_ek41 = (ImageView) findViewById(R.id.vector_ek41);
		vector_ek42 = (ImageView) findViewById(R.id.vector_ek42);
		vector_ek43 = (ImageView) findViewById(R.id.vector_ek43);
		vector_ek44 = (ImageView) findViewById(R.id.vector_ek44);
		vector_ek45 = (ImageView) findViewById(R.id.vector_ek45);
		vector_ek46 = (ImageView) findViewById(R.id.vector_ek46);
		vector_ek47 = (ImageView) findViewById(R.id.vector_ek47);
		vector_ek48 = (ImageView) findViewById(R.id.vector_ek48);
		vector_ek49 = (ImageView) findViewById(R.id.vector_ek49);
		vector_ek50 = (ImageView) findViewById(R.id.vector_ek50);
		vector_ek51 = (ImageView) findViewById(R.id.vector_ek51);
		vector_ek52 = (ImageView) findViewById(R.id.vector_ek52);
		vector_ek53 = (ImageView) findViewById(R.id.vector_ek53);
		vector_ek54 = (ImageView) findViewById(R.id.vector_ek54);
		vector_ek55 = (ImageView) findViewById(R.id.vector_ek55);
		vector_ek56 = (ImageView) findViewById(R.id.vector_ek56);
		vector_ek57 = (ImageView) findViewById(R.id.vector_ek57);
		vector_ek58 = (ImageView) findViewById(R.id.vector_ek58);
		vector_ek59 = (ImageView) findViewById(R.id.vector_ek59);
		vector_ek60 = (ImageView) findViewById(R.id.vector_ek60);
		vector_ek61 = (ImageView) findViewById(R.id.vector_ek61);
		vector_ek62 = (ImageView) findViewById(R.id.vector_ek62);
		vector_ek63 = (ImageView) findViewById(R.id.vector_ek63);
		vector_ek64 = (ImageView) findViewById(R.id.vector_ek64);
		vector_ek65 = (ImageView) findViewById(R.id.vector_ek65);
		vector_ek66 = (ImageView) findViewById(R.id.vector_ek66);
		vector_ek67 = (ImageView) findViewById(R.id.vector_ek67);
		vector_ek68 = (ImageView) findViewById(R.id.vector_ek68);
		vector_ek69 = (ImageView) findViewById(R.id.vector_ek69);
		vector_ek70 = (ImageView) findViewById(R.id.vector_ek70);
		vector_ek71 = (ImageView) findViewById(R.id.vector_ek71);
		vector_ek72 = (ImageView) findViewById(R.id.vector_ek72);
		vector_ek73 = (ImageView) findViewById(R.id.vector_ek73);
		vector_ek74 = (ImageView) findViewById(R.id.vector_ek74);
		vector_ek75 = (ImageView) findViewById(R.id.vector_ek75);
		vector_ek76 = (ImageView) findViewById(R.id.vector_ek76);
		vector_ek77 = (ImageView) findViewById(R.id.vector_ek77);
		text_ek1 = (TextView) findViewById(R.id.text_ek1);
		vector_ek78 = (ImageView) findViewById(R.id.vector_ek78);
		vector_ek79 = (ImageView) findViewById(R.id.vector_ek79);
		vector_ek80 = (ImageView) findViewById(R.id.vector_ek80);
		vector_ek81 = (ImageView) findViewById(R.id.vector_ek81);
		vector_ek82 = (ImageView) findViewById(R.id.vector_ek82);
		vector_ek83 = (ImageView) findViewById(R.id.vector_ek83);
		vector_ek84 = (ImageView) findViewById(R.id.vector_ek84);
		vector_ek85 = (ImageView) findViewById(R.id.vector_ek85);
		vector_ek86 = (ImageView) findViewById(R.id.vector_ek86);
		vector_ek87 = (ImageView) findViewById(R.id.vector_ek87);
		vector_ek88 = (ImageView) findViewById(R.id.vector_ek88);
		vector_ek89 = (ImageView) findViewById(R.id.vector_ek89);
		vector_ek90 = (ImageView) findViewById(R.id.vector_ek90);
		vector_ek91 = (ImageView) findViewById(R.id.vector_ek91);
		vector_ek92 = (ImageView) findViewById(R.id.vector_ek92);
		vector_ek93 = (ImageView) findViewById(R.id.vector_ek93);
		vector_ek94 = (ImageView) findViewById(R.id.vector_ek94);
		vector_ek95 = (ImageView) findViewById(R.id.vector_ek95);
		vector_ek96 = (ImageView) findViewById(R.id.vector_ek96);
		vector_ek97 = (ImageView) findViewById(R.id.vector_ek97);
		vector_ek98 = (ImageView) findViewById(R.id.vector_ek98);
		vector_ek99 = (ImageView) findViewById(R.id.vector_ek99);
		vector_ek100 = (ImageView) findViewById(R.id.vector_ek100);
		vector_ek101 = (ImageView) findViewById(R.id.vector_ek101);
		vector_ek102 = (ImageView) findViewById(R.id.vector_ek102);
		vector_ek103 = (ImageView) findViewById(R.id.vector_ek103);
		vector_ek104 = (ImageView) findViewById(R.id.vector_ek104);
		vector_ek105 = (ImageView) findViewById(R.id.vector_ek105);
		vector_ek106 = (ImageView) findViewById(R.id.vector_ek106);
		vector_ek107 = (ImageView) findViewById(R.id.vector_ek107);
		vector_ek108 = (ImageView) findViewById(R.id.vector_ek108);
		vector_ek109 = (ImageView) findViewById(R.id.vector_ek109);
		vector_ek110 = (ImageView) findViewById(R.id.vector_ek110);
		vector_ek111 = (ImageView) findViewById(R.id.vector_ek111);
		vector_ek112 = (ImageView) findViewById(R.id.vector_ek112);
		vector_ek113 = (ImageView) findViewById(R.id.vector_ek113);
		vector_ek114 = (ImageView) findViewById(R.id.vector_ek114);
		vector_ek115 = (ImageView) findViewById(R.id.vector_ek115);
		vector_ek116 = (ImageView) findViewById(R.id.vector_ek116);
		vector_ek117 = (ImageView) findViewById(R.id.vector_ek117);
		vector_ek118 = (ImageView) findViewById(R.id.vector_ek118);
		vector_ek119 = (ImageView) findViewById(R.id.vector_ek119);
		vector_ek120 = (ImageView) findViewById(R.id.vector_ek120);
		vector_ek121 = (ImageView) findViewById(R.id.vector_ek121);
		vector_ek122 = (ImageView) findViewById(R.id.vector_ek122);
		vector_ek123 = (ImageView) findViewById(R.id.vector_ek123);
		vector_ek124 = (ImageView) findViewById(R.id.vector_ek124);
		vector_ek125 = (ImageView) findViewById(R.id.vector_ek125);
		vector_ek126 = (ImageView) findViewById(R.id.vector_ek126);
		vector_ek127 = (ImageView) findViewById(R.id.vector_ek127);
		vector_ek128 = (ImageView) findViewById(R.id.vector_ek128);
		hand = (ImageView) findViewById(R.id.hand);
		text_ek2 = (TextView) findViewById(R.id.text_ek2);
		vector_ek129 = (ImageView) findViewById(R.id.vector_ek129);
		vector_ek130 = (ImageView) findViewById(R.id.vector_ek130);
		vector_ek131 = (ImageView) findViewById(R.id.vector_ek131);
		vector_ek132 = (ImageView) findViewById(R.id.vector_ek132);
		vector_ek133 = (ImageView) findViewById(R.id.vector_ek133);
		vector_ek134 = (ImageView) findViewById(R.id.vector_ek134);
		vector_ek135 = (ImageView) findViewById(R.id.vector_ek135);
		vector_ek136 = (ImageView) findViewById(R.id.vector_ek136);
		vector_ek137 = (ImageView) findViewById(R.id.vector_ek137);
		vector_ek138 = (ImageView) findViewById(R.id.vector_ek138);
		vector_ek139 = (ImageView) findViewById(R.id.vector_ek139);
		vector_ek140 = (ImageView) findViewById(R.id.vector_ek140);
		vector_ek141 = (ImageView) findViewById(R.id.vector_ek141);
		vector_ek142 = (ImageView) findViewById(R.id.vector_ek142);
		vector_ek143 = (ImageView) findViewById(R.id.vector_ek143);
		vector_ek144 = (ImageView) findViewById(R.id.vector_ek144);
		text_ek3 = (TextView) findViewById(R.id.text_ek3);
		vector_ek145 = (ImageView) findViewById(R.id.vector_ek145);
		vector_ek146 = (ImageView) findViewById(R.id.vector_ek146);
		vector_ek147 = (ImageView) findViewById(R.id.vector_ek147);
		vector_ek148 = (ImageView) findViewById(R.id.vector_ek148);
		vector_ek149 = (ImageView) findViewById(R.id.vector_ek149);
		vector_ek150 = (ImageView) findViewById(R.id.vector_ek150);
		vector_ek151 = (ImageView) findViewById(R.id.vector_ek151);
		vector_ek152 = (ImageView) findViewById(R.id.vector_ek152);
		vector_ek153 = (ImageView) findViewById(R.id.vector_ek153);
		vector_ek154 = (ImageView) findViewById(R.id.vector_ek154);
		vector_ek155 = (ImageView) findViewById(R.id.vector_ek155);
		vector_ek156 = (ImageView) findViewById(R.id.vector_ek156);
		vector_ek157 = (ImageView) findViewById(R.id.vector_ek157);
		vector_ek158 = (ImageView) findViewById(R.id.vector_ek158);
		vector_ek159 = (ImageView) findViewById(R.id.vector_ek159);
		vector_ek160 = (ImageView) findViewById(R.id.vector_ek160);
		vector_ek161 = (ImageView) findViewById(R.id.vector_ek161);
		vector_ek162 = (ImageView) findViewById(R.id.vector_ek162);
		vector_ek163 = (ImageView) findViewById(R.id.vector_ek163);
		vector_ek164 = (ImageView) findViewById(R.id.vector_ek164);
		vector_ek165 = (ImageView) findViewById(R.id.vector_ek165);
		vector_ek166 = (ImageView) findViewById(R.id.vector_ek166);
		vector_ek167 = (ImageView) findViewById(R.id.vector_ek167);
		vector_ek168 = (ImageView) findViewById(R.id.vector_ek168);
		vector_ek169 = (ImageView) findViewById(R.id.vector_ek169);
		vector_ek170 = (ImageView) findViewById(R.id.vector_ek170);
		vector_ek171 = (ImageView) findViewById(R.id.vector_ek171);
		vector_ek172 = (ImageView) findViewById(R.id.vector_ek172);
		vector_ek173 = (ImageView) findViewById(R.id.vector_ek173);
		vector_ek174 = (ImageView) findViewById(R.id.vector_ek174);
		vector_ek175 = (ImageView) findViewById(R.id.vector_ek175);
		listen_and_learn = (TextView) findViewById(R.id.listen_and_learn);
		vector_ek189 = (ImageView) findViewById(R.id.vector_ek189);
		vector_ek190 = (ImageView) findViewById(R.id.vector_ek190);
		vector_ek191 = (ImageView) findViewById(R.id.vector_ek191);
		vector_ek192 = (ImageView) findViewById(R.id.vector_ek192);
		vector_ek193 = (ImageView) findViewById(R.id.vector_ek193);
		vector_ek194 = (ImageView) findViewById(R.id.vector_ek194);
		vector_ek195 = (ImageView) findViewById(R.id.vector_ek195);
		vector_ek196 = (ImageView) findViewById(R.id.vector_ek196);
		vector_ek197 = (ImageView) findViewById(R.id.vector_ek197);
		vector_ek198 = (ImageView) findViewById(R.id.vector_ek198);
		vector_ek199 = (ImageView) findViewById(R.id.vector_ek199);
		vector_ek200 = (ImageView) findViewById(R.id.vector_ek200);
		vector_ek201 = (ImageView) findViewById(R.id.vector_ek201);
		vector_ek202 = (ImageView) findViewById(R.id.vector_ek202);
		vector_ek203 = (ImageView) findViewById(R.id.vector_ek203);
		vector_ek204 = (ImageView) findViewById(R.id.vector_ek204);
		vector_ek205 = (ImageView) findViewById(R.id.vector_ek205);
		vector_ek206 = (ImageView) findViewById(R.id.vector_ek206);
		vector_ek207 = (ImageView) findViewById(R.id.vector_ek207);
		vector_ek208 = (ImageView) findViewById(R.id.vector_ek208);
		vector_ek209 = (ImageView) findViewById(R.id.vector_ek209);
		vector_ek210 = (ImageView) findViewById(R.id.vector_ek210);
		vector_ek211 = (ImageView) findViewById(R.id.vector_ek211);
		vector_ek212 = (ImageView) findViewById(R.id.vector_ek212);
		vector_ek213 = (ImageView) findViewById(R.id.vector_ek213);
		vector_ek214 = (ImageView) findViewById(R.id.vector_ek214);
		vector_ek215 = (ImageView) findViewById(R.id.vector_ek215);
		_100 = (TextView) findViewById(R.id._100);
		blob_ek6 = (ImageView) findViewById(R.id.blob_ek6);
		path = (ImageView) findViewById(R.id.path);
		path_ek1 = (ImageView) findViewById(R.id.path_ek1);
		shape = (ImageView) findViewById(R.id.shape);
		oval = (ImageView) findViewById(R.id.oval);
		oval_copy = (ImageView) findViewById(R.id.oval_copy);
		shape_ek1 = (ImageView) findViewById(R.id.shape_ek1);
		path_30 = (ImageView) findViewById(R.id.path_30);
		shape_ek2 = (ImageView) findViewById(R.id.shape_ek2);
		path_ek2 = (ImageView) findViewById(R.id.path_ek2);
		path_ek3 = (ImageView) findViewById(R.id.path_ek3);
		listen_and_learn_ek1 = (TextView) findViewById(R.id.listen_and_learn_ek1);
		vector_ek216 = (ImageView) findViewById(R.id.vector_ek216);
		vector_ek217 = (ImageView) findViewById(R.id.vector_ek217);
		vector_ek218 = (ImageView) findViewById(R.id.vector_ek218);
		vector_ek219 = (ImageView) findViewById(R.id.vector_ek219);
		vector_ek220 = (ImageView) findViewById(R.id.vector_ek220);
		vector_ek221 = (ImageView) findViewById(R.id.vector_ek221);
		vector_ek222 = (ImageView) findViewById(R.id.vector_ek222);
		vector_ek223 = (ImageView) findViewById(R.id.vector_ek223);
		vector_ek224 = (ImageView) findViewById(R.id.vector_ek224);
		vector_ek225 = (ImageView) findViewById(R.id.vector_ek225);
		vector_ek226 = (ImageView) findViewById(R.id.vector_ek226);
		vector_ek227 = (ImageView) findViewById(R.id.vector_ek227);
		vector_ek228 = (ImageView) findViewById(R.id.vector_ek228);
		vector_ek229 = (ImageView) findViewById(R.id.vector_ek229);
		vector_ek230 = (ImageView) findViewById(R.id.vector_ek230);
		vector_ek231 = (ImageView) findViewById(R.id.vector_ek231);
		vector_ek232 = (ImageView) findViewById(R.id.vector_ek232);
		vector_ek233 = (ImageView) findViewById(R.id.vector_ek233);
		vector_ek234 = (ImageView) findViewById(R.id.vector_ek234);
		vector_ek235 = (ImageView) findViewById(R.id.vector_ek235);
		vector_ek236 = (ImageView) findViewById(R.id.vector_ek236);
		vector_ek237 = (ImageView) findViewById(R.id.vector_ek237);
		vector_ek238 = (ImageView) findViewById(R.id.vector_ek238);
		vector_ek239 = (ImageView) findViewById(R.id.vector_ek239);
		vector_ek240 = (ImageView) findViewById(R.id.vector_ek240);
		vector_ek241 = (ImageView) findViewById(R.id.vector_ek241);
		vector_ek242 = (ImageView) findViewById(R.id.vector_ek242);
		_100_ek1 = (TextView) findViewById(R.id._100_ek1);
		new_games_ek1 = (TextView) findViewById(R.id.new_games_ek1);
		vector_ek243 = (ImageView) findViewById(R.id.vector_ek243);
		subitle = (TextView) findViewById(R.id.subitle);
		vector_ek244 = (ImageView) findViewById(R.id.vector_ek244);
		vector_ek245 = (ImageView) findViewById(R.id.vector_ek245);
		vector_ek246 = (ImageView) findViewById(R.id.vector_ek246);
		vector_ek247 = (ImageView) findViewById(R.id.vector_ek247);
		vector_ek248 = (ImageView) findViewById(R.id.vector_ek248);
		vector_ek249 = (ImageView) findViewById(R.id.vector_ek249);
		vector_ek250 = (ImageView) findViewById(R.id.vector_ek250);
		vector_ek251 = (ImageView) findViewById(R.id.vector_ek251);
		vector_ek252 = (ImageView) findViewById(R.id.vector_ek252);
		vector_ek253 = (ImageView) findViewById(R.id.vector_ek253);
		vector_ek254 = (ImageView) findViewById(R.id.vector_ek254);
		vector_ek255 = (ImageView) findViewById(R.id.vector_ek255);
		vector_ek256 = (ImageView) findViewById(R.id.vector_ek256);
		vector_ek257 = (ImageView) findViewById(R.id.vector_ek257);
		vector_ek258 = (ImageView) findViewById(R.id.vector_ek258);
		vector_ek259 = (ImageView) findViewById(R.id.vector_ek259);
		vector_ek260 = (ImageView) findViewById(R.id.vector_ek260);
		vector_ek261 = (ImageView) findViewById(R.id.vector_ek261);
		vector_ek262 = (ImageView) findViewById(R.id.vector_ek262);
		vector_ek263 = (ImageView) findViewById(R.id.vector_ek263);
		vector_ek264 = (ImageView) findViewById(R.id.vector_ek264);
		vector_ek265 = (ImageView) findViewById(R.id.vector_ek265);
		vector_ek266 = (ImageView) findViewById(R.id.vector_ek266);
		vector_ek267 = (ImageView) findViewById(R.id.vector_ek267);
		vector_ek268 = (ImageView) findViewById(R.id.vector_ek268);
		vector_ek269 = (ImageView) findViewById(R.id.vector_ek269);
		vector_ek270 = (ImageView) findViewById(R.id.vector_ek270);
		vector_ek271 = (ImageView) findViewById(R.id.vector_ek271);
		vector_ek272 = (ImageView) findViewById(R.id.vector_ek272);
		listen_and_learn_ek2 = (TextView) findViewById(R.id.listen_and_learn_ek2);
		vector_ek273 = (ImageView) findViewById(R.id.vector_ek273);
		vector_ek274 = (ImageView) findViewById(R.id.vector_ek274);
		vector_ek275 = (ImageView) findViewById(R.id.vector_ek275);
		vector_ek276 = (ImageView) findViewById(R.id.vector_ek276);
		vector_ek277 = (ImageView) findViewById(R.id.vector_ek277);
		vector_ek278 = (ImageView) findViewById(R.id.vector_ek278);
		vector_ek279 = (ImageView) findViewById(R.id.vector_ek279);
		vector_ek280 = (ImageView) findViewById(R.id.vector_ek280);
		vector_ek281 = (ImageView) findViewById(R.id.vector_ek281);
		vector_ek282 = (ImageView) findViewById(R.id.vector_ek282);
		vector_ek283 = (ImageView) findViewById(R.id.vector_ek283);
		vector_ek284 = (ImageView) findViewById(R.id.vector_ek284);
		vector_ek285 = (ImageView) findViewById(R.id.vector_ek285);
		vector_ek286 = (ImageView) findViewById(R.id.vector_ek286);
		vector_ek287 = (ImageView) findViewById(R.id.vector_ek287);
		vector_ek288 = (ImageView) findViewById(R.id.vector_ek288);
		vector_ek289 = (ImageView) findViewById(R.id.vector_ek289);
		vector_ek290 = (ImageView) findViewById(R.id.vector_ek290);
		vector_ek291 = (ImageView) findViewById(R.id.vector_ek291);
		vector_ek292 = (ImageView) findViewById(R.id.vector_ek292);
		vector_ek293 = (ImageView) findViewById(R.id.vector_ek293);
		vector_ek294 = (ImageView) findViewById(R.id.vector_ek294);
		vector_ek295 = (ImageView) findViewById(R.id.vector_ek295);
		vector_ek296 = (ImageView) findViewById(R.id.vector_ek296);
		vector_ek297 = (ImageView) findViewById(R.id.vector_ek297);
		vector_ek298 = (ImageView) findViewById(R.id.vector_ek298);
		vector_ek299 = (ImageView) findViewById(R.id.vector_ek299);
		_100_ek2 = (TextView) findViewById(R.id._100_ek2);
		blob_ek7 = (ImageView) findViewById(R.id.blob_ek7);
		whites_ek2 = (ImageView) findViewById(R.id.whites_ek2);
		whites_ek3 = (ImageView) findViewById(R.id.whites_ek3);
		shadow = (ImageView) findViewById(R.id.shadow);
		whites_ek4 = (ImageView) findViewById(R.id.whites_ek4);
		shadow_ek1 = (ImageView) findViewById(R.id.shadow_ek1);
		stroke_ek25 = (ImageView) findViewById(R.id.stroke_ek25);
		whites_ek5 = (ImageView) findViewById(R.id.whites_ek5);
		shape_ek3 = (ImageView) findViewById(R.id.shape_ek3);
		shadow_ek2 = (ImageView) findViewById(R.id.shadow_ek2);
		shape_ek4 = (ImageView) findViewById(R.id.shape_ek4);
		whites_ek6 = (ImageView) findViewById(R.id.whites_ek6);
		whites_ek7 = (ImageView) findViewById(R.id.whites_ek7);
		whites_ek8 = (ImageView) findViewById(R.id.whites_ek8);
		whites_ek9 = (ImageView) findViewById(R.id.whites_ek9);
		whites_ek10 = (ImageView) findViewById(R.id.whites_ek10);
		whites_ek11 = (ImageView) findViewById(R.id.whites_ek11);
		whites_ek12 = (ImageView) findViewById(R.id.whites_ek12);
		whites_ek13 = (ImageView) findViewById(R.id.whites_ek13);
		whites_ek14 = (ImageView) findViewById(R.id.whites_ek14);
		whites_ek15 = (ImageView) findViewById(R.id.whites_ek15);
		whites_ek16 = (ImageView) findViewById(R.id.whites_ek16);
		whites_ek17 = (ImageView) findViewById(R.id.whites_ek17);
		whites_ek18 = (ImageView) findViewById(R.id.whites_ek18);
		whites_ek19 = (ImageView) findViewById(R.id.whites_ek19);
		whites_ek20 = (ImageView) findViewById(R.id.whites_ek20);
		whites_ek21 = (ImageView) findViewById(R.id.whites_ek21);
		whites_ek22 = (ImageView) findViewById(R.id.whites_ek22);
		whites_ek23 = (ImageView) findViewById(R.id.whites_ek23);
		whites_ek24 = (ImageView) findViewById(R.id.whites_ek24);
		whites_ek25 = (ImageView) findViewById(R.id.whites_ek25);
		whites_ek26 = (ImageView) findViewById(R.id.whites_ek26);
		whites_ek27 = (ImageView) findViewById(R.id.whites_ek27);
		whites_ek28 = (ImageView) findViewById(R.id.whites_ek28);
		whites_ek29 = (ImageView) findViewById(R.id.whites_ek29);
		whites_ek30 = (ImageView) findViewById(R.id.whites_ek30);
		whites_ek31 = (ImageView) findViewById(R.id.whites_ek31);
		whites_ek32 = (ImageView) findViewById(R.id.whites_ek32);
		whites_ek33 = (ImageView) findViewById(R.id.whites_ek33);
		whites_ek34 = (ImageView) findViewById(R.id.whites_ek34);
		whites_ek35 = (ImageView) findViewById(R.id.whites_ek35);
		whites_ek36 = (ImageView) findViewById(R.id.whites_ek36);
		whites_ek37 = (ImageView) findViewById(R.id.whites_ek37);
		whites_ek38 = (ImageView) findViewById(R.id.whites_ek38);
		whites_ek39 = (ImageView) findViewById(R.id.whites_ek39);
		whites_ek40 = (ImageView) findViewById(R.id.whites_ek40);
		whites_ek41 = (ImageView) findViewById(R.id.whites_ek41);
		whites_ek42 = (ImageView) findViewById(R.id.whites_ek42);
		whites_ek43 = (ImageView) findViewById(R.id.whites_ek43);
		whites_ek44 = (ImageView) findViewById(R.id.whites_ek44);
		whites_ek45 = (ImageView) findViewById(R.id.whites_ek45);
		whites_ek46 = (ImageView) findViewById(R.id.whites_ek46);
		whites_ek47 = (ImageView) findViewById(R.id.whites_ek47);
		whites_ek48 = (ImageView) findViewById(R.id.whites_ek48);
		whites_ek49 = (ImageView) findViewById(R.id.whites_ek49);
		whites_ek50 = (ImageView) findViewById(R.id.whites_ek50);
		whites_ek51 = (ImageView) findViewById(R.id.whites_ek51);
		whites_ek52 = (ImageView) findViewById(R.id.whites_ek52);
		whites_ek53 = (ImageView) findViewById(R.id.whites_ek53);
		whites_ek54 = (ImageView) findViewById(R.id.whites_ek54);
		whites_ek55 = (ImageView) findViewById(R.id.whites_ek55);
		whites_ek56 = (ImageView) findViewById(R.id.whites_ek56);
		whites_ek57 = (ImageView) findViewById(R.id.whites_ek57);
		whites_ek58 = (ImageView) findViewById(R.id.whites_ek58);
		whites_ek59 = (ImageView) findViewById(R.id.whites_ek59);
		whites_ek60 = (ImageView) findViewById(R.id.whites_ek60);
		whites_ek61 = (ImageView) findViewById(R.id.whites_ek61);
		whites_ek62 = (ImageView) findViewById(R.id.whites_ek62);
		whites_ek63 = (ImageView) findViewById(R.id.whites_ek63);
		whites_ek64 = (ImageView) findViewById(R.id.whites_ek64);
		whites_ek65 = (ImageView) findViewById(R.id.whites_ek65);
		whites_ek66 = (ImageView) findViewById(R.id.whites_ek66);
		whites_ek67 = (ImageView) findViewById(R.id.whites_ek67);
		whites_ek68 = (ImageView) findViewById(R.id.whites_ek68);
		whites_ek69 = (ImageView) findViewById(R.id.whites_ek69);
		whites_ek70 = (ImageView) findViewById(R.id.whites_ek70);
		whites_ek71 = (ImageView) findViewById(R.id.whites_ek71);
		whites_ek72 = (ImageView) findViewById(R.id.whites_ek72);
		whites_ek73 = (ImageView) findViewById(R.id.whites_ek73);
		whites_ek74 = (ImageView) findViewById(R.id.whites_ek74);
		whites_ek75 = (ImageView) findViewById(R.id.whites_ek75);
		whites_ek76 = (ImageView) findViewById(R.id.whites_ek76);
		whites_ek77 = (ImageView) findViewById(R.id.whites_ek77);
		whites_ek78 = (ImageView) findViewById(R.id.whites_ek78);
		whites_ek79 = (ImageView) findViewById(R.id.whites_ek79);
		stroke_ek26 = (ImageView) findViewById(R.id.stroke_ek26);
		stroke_ek27 = (ImageView) findViewById(R.id.stroke_ek27);
		stroke_ek28 = (ImageView) findViewById(R.id.stroke_ek28);
		whites_ek80 = (ImageView) findViewById(R.id.whites_ek80);
		shape_ek5 = (ImageView) findViewById(R.id.shape_ek5);
		whites_ek81 = (ImageView) findViewById(R.id.whites_ek81);
		whites_ek82 = (ImageView) findViewById(R.id.whites_ek82);
		shadow_ek3 = (ImageView) findViewById(R.id.shadow_ek3);
		shadow_ek4 = (ImageView) findViewById(R.id.shadow_ek4);
		listen_and_learn_ek3 = (TextView) findViewById(R.id.listen_and_learn_ek3);
		vector_ek300 = (ImageView) findViewById(R.id.vector_ek300);
		vector_ek301 = (ImageView) findViewById(R.id.vector_ek301);
		vector_ek302 = (ImageView) findViewById(R.id.vector_ek302);
		vector_ek303 = (ImageView) findViewById(R.id.vector_ek303);
		vector_ek304 = (ImageView) findViewById(R.id.vector_ek304);
		vector_ek305 = (ImageView) findViewById(R.id.vector_ek305);
		vector_ek306 = (ImageView) findViewById(R.id.vector_ek306);
		vector_ek307 = (ImageView) findViewById(R.id.vector_ek307);
		vector_ek308 = (ImageView) findViewById(R.id.vector_ek308);
		vector_ek309 = (ImageView) findViewById(R.id.vector_ek309);
		vector_ek310 = (ImageView) findViewById(R.id.vector_ek310);
		vector_ek311 = (ImageView) findViewById(R.id.vector_ek311);
		vector_ek312 = (ImageView) findViewById(R.id.vector_ek312);
		vector_ek313 = (ImageView) findViewById(R.id.vector_ek313);
		vector_ek314 = (ImageView) findViewById(R.id.vector_ek314);
		vector_ek315 = (ImageView) findViewById(R.id.vector_ek315);
		vector_ek316 = (ImageView) findViewById(R.id.vector_ek316);
		vector_ek317 = (ImageView) findViewById(R.id.vector_ek317);
		vector_ek318 = (ImageView) findViewById(R.id.vector_ek318);
		vector_ek319 = (ImageView) findViewById(R.id.vector_ek319);
		vector_ek320 = (ImageView) findViewById(R.id.vector_ek320);
		vector_ek321 = (ImageView) findViewById(R.id.vector_ek321);
		vector_ek322 = (ImageView) findViewById(R.id.vector_ek322);
		vector_ek323 = (ImageView) findViewById(R.id.vector_ek323);
		vector_ek324 = (ImageView) findViewById(R.id.vector_ek324);
		vector_ek325 = (ImageView) findViewById(R.id.vector_ek325);
		vector_ek326 = (ImageView) findViewById(R.id.vector_ek326);
		_100_ek3 = (TextView) findViewById(R.id._100_ek3);
		blob_ek8 = (ImageView) findViewById(R.id.blob_ek8);
		vector_ek327 = (ImageView) findViewById(R.id.vector_ek327);
		vector_ek328 = (ImageView) findViewById(R.id.vector_ek328);
		vector_ek329 = (ImageView) findViewById(R.id.vector_ek329);
		vector_ek330 = (ImageView) findViewById(R.id.vector_ek330);
		vector_ek331 = (ImageView) findViewById(R.id.vector_ek331);
		vector_ek332 = (ImageView) findViewById(R.id.vector_ek332);
		vector_ek333 = (ImageView) findViewById(R.id.vector_ek333);
		vector_ek334 = (ImageView) findViewById(R.id.vector_ek334);
		vector_ek335 = (ImageView) findViewById(R.id.vector_ek335);
		vector_ek336 = (ImageView) findViewById(R.id.vector_ek336);
		vector_ek337 = (ImageView) findViewById(R.id.vector_ek337);
		vector_ek338 = (ImageView) findViewById(R.id.vector_ek338);
		vector_ek339 = (ImageView) findViewById(R.id.vector_ek339);
		vector_ek340 = (ImageView) findViewById(R.id.vector_ek340);
		vector_ek341 = (ImageView) findViewById(R.id.vector_ek341);
		vector_ek342 = (ImageView) findViewById(R.id.vector_ek342);
		vector_ek343 = (ImageView) findViewById(R.id.vector_ek343);
		vector_ek344 = (ImageView) findViewById(R.id.vector_ek344);
		vector_ek345 = (ImageView) findViewById(R.id.vector_ek345);
		vector_ek346 = (ImageView) findViewById(R.id.vector_ek346);
		vector_ek347 = (ImageView) findViewById(R.id.vector_ek347);
		vector_ek348 = (ImageView) findViewById(R.id.vector_ek348);
		vector_ek349 = (ImageView) findViewById(R.id.vector_ek349);
		vector_ek350 = (ImageView) findViewById(R.id.vector_ek350);
		vector_ek351 = (ImageView) findViewById(R.id.vector_ek351);
		listen_and_learn_ek4 = (TextView) findViewById(R.id.listen_and_learn_ek4);
		vector_ek352 = (ImageView) findViewById(R.id.vector_ek352);
		vector_ek353 = (ImageView) findViewById(R.id.vector_ek353);
		vector_ek354 = (ImageView) findViewById(R.id.vector_ek354);
		vector_ek355 = (ImageView) findViewById(R.id.vector_ek355);
		vector_ek356 = (ImageView) findViewById(R.id.vector_ek356);
		vector_ek357 = (ImageView) findViewById(R.id.vector_ek357);
		vector_ek358 = (ImageView) findViewById(R.id.vector_ek358);
		vector_ek359 = (ImageView) findViewById(R.id.vector_ek359);
		vector_ek360 = (ImageView) findViewById(R.id.vector_ek360);
		vector_ek361 = (ImageView) findViewById(R.id.vector_ek361);
		vector_ek362 = (ImageView) findViewById(R.id.vector_ek362);
		vector_ek363 = (ImageView) findViewById(R.id.vector_ek363);
		vector_ek364 = (ImageView) findViewById(R.id.vector_ek364);
		vector_ek365 = (ImageView) findViewById(R.id.vector_ek365);
		vector_ek366 = (ImageView) findViewById(R.id.vector_ek366);
		vector_ek367 = (ImageView) findViewById(R.id.vector_ek367);
		vector_ek368 = (ImageView) findViewById(R.id.vector_ek368);
		vector_ek369 = (ImageView) findViewById(R.id.vector_ek369);
		vector_ek370 = (ImageView) findViewById(R.id.vector_ek370);
		vector_ek371 = (ImageView) findViewById(R.id.vector_ek371);
		vector_ek372 = (ImageView) findViewById(R.id.vector_ek372);
		vector_ek373 = (ImageView) findViewById(R.id.vector_ek373);
		vector_ek374 = (ImageView) findViewById(R.id.vector_ek374);
		vector_ek375 = (ImageView) findViewById(R.id.vector_ek375);
		vector_ek376 = (ImageView) findViewById(R.id.vector_ek376);
		vector_ek377 = (ImageView) findViewById(R.id.vector_ek377);
		vector_ek378 = (ImageView) findViewById(R.id.vector_ek378);
		_100_ek4 = (TextView) findViewById(R.id._100_ek4);
		rectangle_6 = (View) findViewById(R.id.rectangle_6);
		vector_ek379 = (ImageView) findViewById(R.id.vector_ek379);
		complete_other_games_to_unlock = (TextView) findViewById(R.id.complete_other_games_to_unlock);
		vector_ek380 = (ImageView) findViewById(R.id.vector_ek380);
		vector_ek381 = (ImageView) findViewById(R.id.vector_ek381);
		vector_ek382 = (ImageView) findViewById(R.id.vector_ek382);
		vector_ek383 = (ImageView) findViewById(R.id.vector_ek383);
		vector_ek384 = (ImageView) findViewById(R.id.vector_ek384);
		vector_ek385 = (ImageView) findViewById(R.id.vector_ek385);
		vector_ek386 = (ImageView) findViewById(R.id.vector_ek386);
		vector_ek387 = (ImageView) findViewById(R.id.vector_ek387);
		vector_ek388 = (ImageView) findViewById(R.id.vector_ek388);
		discover_ek1 = (TextView) findViewById(R.id.discover_ek1);
		vector_ek389 = (ImageView) findViewById(R.id.vector_ek389);
		vector_ek390 = (ImageView) findViewById(R.id.vector_ek390);
		vector_ek391 = (ImageView) findViewById(R.id.vector_ek391);
		vector_ek392 = (ImageView) findViewById(R.id.vector_ek392);
		vector_ek393 = (ImageView) findViewById(R.id.vector_ek393);
		vector_ek394 = (ImageView) findViewById(R.id.vector_ek394);
		vector_ek395 = (ImageView) findViewById(R.id.vector_ek395);
		vector_ek396 = (ImageView) findViewById(R.id.vector_ek396);
		search_ek1 = (TextView) findViewById(R.id.search_ek1);
		vector_ek397 = (ImageView) findViewById(R.id.vector_ek397);
		vector_ek398 = (ImageView) findViewById(R.id.vector_ek398);
		vector_ek399 = (ImageView) findViewById(R.id.vector_ek399);
		vector_ek400 = (ImageView) findViewById(R.id.vector_ek400);
		favorites = (TextView) findViewById(R.id.favorites);
		vector_ek401 = (ImageView) findViewById(R.id.vector_ek401);
		vector_ek402 = (ImageView) findViewById(R.id.vector_ek402);
		vector_ek403 = (ImageView) findViewById(R.id.vector_ek403);
		vector_ek404 = (ImageView) findViewById(R.id.vector_ek404);
		vector_ek405 = (ImageView) findViewById(R.id.vector_ek405);
		vector_ek406 = (ImageView) findViewById(R.id.vector_ek406);
		vector_ek407 = (ImageView) findViewById(R.id.vector_ek407);
		vector_ek408 = (ImageView) findViewById(R.id.vector_ek408);
		vector_ek409 = (ImageView) findViewById(R.id.vector_ek409);
		vector_ek410 = (ImageView) findViewById(R.id.vector_ek410);
		vector_ek411 = (ImageView) findViewById(R.id.vector_ek411);
		vector_ek412 = (ImageView) findViewById(R.id.vector_ek412);
		vector_ek413 = (ImageView) findViewById(R.id.vector_ek413);
		vector_ek414 = (ImageView) findViewById(R.id.vector_ek414);
		vector_ek415 = (ImageView) findViewById(R.id.vector_ek415);
		vector_ek416 = (ImageView) findViewById(R.id.vector_ek416);
		profile_ek1 = (TextView) findViewById(R.id.profile_ek1);
		home_indicator_ek1 = (View) findViewById(R.id.home_indicator_ek1);
		rectangle_69 = (ImageView) findViewById(R.id.rectangle_69);
		treasure_chest = (ImageView) findViewById(R.id.treasure_chest);
		_1432_xp = (TextView) findViewById(R.id._1432_xp);
		fire = (ImageView) findViewById(R.id.fire);
		_3 = (TextView) findViewById(R.id._3);
		stitched_heart = (ImageView) findViewById(R.id.stitched_heart);
		_7 = (TextView) findViewById(R.id._7);
		diamond = (ImageView) findViewById(R.id.diamond);
		_22 = (TextView) findViewById(R.id._22);
		woman_chilling_on_vacation_in_a_pool_ring_with_cocktail = (ImageView) findViewById(R.id.woman_chilling_on_vacation_in_a_pool_ring_with_cocktail);
		_9_41_ek1 = (ImageView) findViewById(R.id._9_41_ek1);
		rectangle_ek2 = (ImageView) findViewById(R.id.rectangle_ek2);
		combined_shape_ek1 = (ImageView) findViewById(R.id.combined_shape_ek1);
		rectangle_ek3 = (ImageView) findViewById(R.id.rectangle_ek3);
		wifi_ek1 = (ImageView) findViewById(R.id.wifi_ek1);
		mobile_signal_ek1 = (ImageView) findViewById(R.id.mobile_signal_ek1);
		indicator_ek1 = (View) findViewById(R.id.indicator_ek1);
		welcome_back_ = (TextView) findViewById(R.id.welcome_back_);
	
		
		//custom code goes here
	
	}
}
	
	